### ISSUE TITLE
'IntensityForm' is not vertically centered

### ISSUE THREAD

**Issue by 87prashant** [87prashant/MindChart#4]
![Screenshot 2022-10-08 215950](https://user-images.githubusercontent.com/106697681/194717700-213b5468-3f68-467d-b84c-bcfea2c7528f.png)

**Comment by shubhamrawat090** [comment]
Hey @87prashant I am new to open source and react as well. Can I work on this? Please assign it to me if you wish to.

**Comment by 87prashant** [comment]
Hi @shubhamrawat090! good to have you here. I am also new to Open-Source too.
> Can I work on this? Please assign it to me if you wish to

of course, any help is appreciated.
> Also let me know how to reproduce this issue.

You can reproduce it by clicking on any of the emotions in the form.
